* Beginning

You wake up in a place. You have no idea why you have been locked in this place.

Beside you, you see a robot. The robot actually looks more like a dog than a robot. There is nothing else in this place. 

[img]

The robot also sees you and it says:

"Hi! _Emi_ is here. Welcome to the first plane. And actually Emi's preferred pronoun is 'she'."

You look at her and her "stomach" is actually a computer terminal.

#+BEGIN_QUOTE
Why are you here?
#+END_QUOTE

Actually, it's you who wanted to ask the same question.

And emi says: "Emi will show you why you are here and how to get out of this dungeon."

You think: What? I am in a dungeon? 

Emi's terminal display the following instructions:

#+BEGIN_QUOTE
FOLLOW THE INSTRUCTIONS
- - - -
The following is a _code block_. You can _evaluate_ the following code block by moving the cursor inside it and then press ~C-c C-c. Depending on your setting, it might ask you to confirm the evaluation of the code inside it.
- - - - -
#+END_QUOTE

You are not 100% sure what the instructions mean. But you figured to give it a try. And you see something below, perhaps that's a code block.

#+BEGIN_SRC emacs-lisp
  (load-file "source.el")
  (enter-the-dungeon)
#+END_SRC

#+RESULTS:

